In [13]:
%load_ext lab_black

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black


In [14]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import rankdata

In [15]:
y = np.concatenate((np.zeros(10), np.ones(10)))
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [16]:
pred = np.random.rand(20)
np.round(pred)

array([0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 0.])

In [17]:
# Distance measure
dm = np.round(np.random.uniform(0.1, 10, size=len(pred)), 2)
dm

array([4.89, 4.3 , 0.24, 6.25, 6.49, 6.35, 0.99, 7.93, 1.15, 0.64, 9.7 ,
       1.19, 1.91, 7.54, 5.4 , 8.56, 9.62, 8.38, 9.8 , 5.47])

In [18]:
def permROC(y_true, y_pred, dmeaure, n_perm):
    perm_auc = np.zeros(n_perm)

    y_pred = np.round(y_pred).astype(int)
    idx_pred0 = np.where(y_pred == 0)[0]
    idx_pred1 = np.where(y_pred == 1)[0]
    n_pred0 = len(idx_pred0)
    n_pred1 = len(idx_pred1)

    n_true0 = np.sum(y_true == 0)
    n_true1 = np.sum(y_true == 1)

    idx_true0 = np.where(y_true == 0)[0]

    prem_dmeas = np.zeros(len(dmeaure))

    for i in range(n_perm):
        perm_idx0 = idx_pred0[np.random.permutation(n_pred0)]
        perm_idx1 = idx_pred1[np.random.permutation(n_pred1)]

        prem_dmeas[idx_pred0] = dmeaure[perm_idx0]
        prem_dmeas[idx_pred1] = dmeaure[perm_idx1]

        ranks = rankdata(prem_dmeas)

        s1 = np.sum(ranks[idx_true0])

        auc = (s1 - (n_true0 * (n_true0 + 1) / 2)) / (n_true0 * n_true1)
        perm_auc[i] = auc
    significance_val = np.percentile(perm_auc, 95)

    return significance_val, perm_auc

In [20]:
sval, perm_auc = permROC(y, pred, dm, 10)
print(sval)
print(perm_auc)

0.6949999999999998
[0.59 0.45 0.35 0.64 0.58 0.52 0.43 0.74 0.52 0.4 ]


In [ ]:
from sklearn.metrics import RocCurveDisplay

# TODO: How to plot ROC curve?

# fig, ax = plt.subplots(figsize=(8, 8))
# roc_display = RocCurveDisplay(fpr=fpr, tpr=tpr).plot(ax=ax)
# ax.tick_params(labelsize=14)
# plt.tight_layout()
# plt.show()